### ISSUE TITLE
Change the "share" word

### ISSUE THREAD

**Issue by randinfo** [JamesTheHacker/Facebook-Live-Reactions#9] opened 2016-11-22 20:55 UTC
I tried to change the "share" word to another thing in the fblive.php but it dosnt seem to by applied. What is your instruction to change it ? I've made my changes in the strpos call...

**Comment by JamesTheHacker** [comment] 2016-11-22 20:59
If you want to search comments for a different word change the following line:

    if (strpos(strtolower($comment['message']), 'share') 

... replace `share` with whatever word you like. Keep it lowercase. I will update the script shortly so this can be set within the `settings.php` file. That should work fine.

**Comment by randinfo** [comment] 2016-11-22 21:24
Ok that's what i've done but i dont seem to work.... will wate for your merge. I tried the other branch and i think there is an issue with the post id.
"No POST_ID set. Remeber to set it when you go live"

My post id is set and the live published but the comments array return null. It's wierd

**Comment by JamesTheHacker** [comment] 2016-11-22 21:29
Are you 100% certain the `POST_ID` is correct? The `POST_ID` is in the permalink URL, like this: `https://www.facebook.com/359241181078529/videos/361577590844888/`. Note that it's the 2nd ID ... `361577590844888` and not the first.

If you go [here](https://www.facebook.com/359241181078529/videos/361577590844888/) and watch the stream you will see the shoutouts still work fine. I changed the shoutout keyword multiple times during the stream and had my friend test it.

The `No POST_ID set` error was added in that branch. In the current version it doesn't check so you was never getting the error. Chances are the issue is with the `POST_ID` either not set, or set incorrectly.

Please let me know and I will look into this further.

**Comment by JamesTheHacker** [comment] 2016-11-22 21:37
Also note that when the `POST_ID` is correct you need to stop and start the `fblive.php` script after changing the keyword. Stopping this script and starting it again will not effect the live stream.

**Comment by randinfo** [comment] 2016-11-22 21:43
Yeah that's what i've done. I've made my changes and restart the fblive.php. I'll test it when you merge al your modifications. Maybe it's just i tried it beetween to commits and push don't know...

And for the post ID it's the good one i've used

**Comment by JamesTheHacker** [comment] 2016-11-22 21:46
Are you able to test [this branch](https://github.com/JamesTheHacker/Facebook-Live-Reactions/tree/added_default_shoutout)? This is the one that will be merged.

**Comment by randinfo** [comment] 2016-11-22 21:52
Ok i'll try it now

**Comment by JamesTheHacker** [comment] 2016-11-22 21:53
Thank you 👍

**Comment by randinfo** [comment] 2016-11-22 22:11
I tried it and when i used the Page to comment the shout changed. After that i tried to coment with another account the shout isnt recorded or somthink like that.

**Comment by randinfo** [comment] 2016-11-22 22:11
And the profile image keeps blocked to page one.... and the name used is John Doe

The key word is changed to "aze"

**Comment by JamesTheHacker** [comment] 2016-11-22 22:25
This is strange, I've just set up a stream using "aze" as the keyword and it's working fine: https://www.facebook.com/359241181078529/videos/361600800842567/ ... it `fblive.php` running?

**Comment by randinfo** [comment] 2016-11-22 22:26
yes it's running proved by your vote...

**Comment by randinfo** [comment] 2016-11-22 22:26
Did you commented using your page ?
You are starting the stream with keyword x comment ou x with your page and while fblive.sh is running you stop fblive.php and change keyword to y then comment using y with your page or whatever.

Maybe it's my facebook app... it's realy strange cause the votes are counted and also the comments

**Comment by JamesTheHacker** [comment] 2016-11-22 22:36
I commented with the page, and a real person. Both worked fine. I'm going to add logging to the script. It may give me a better idea about what's going on. Thank you for helping get to the bottom of this.

Out of interest what version of PHP are using?

**Comment by randinfo** [comment] 2016-11-22 22:41
You are welcom and thanks for your share :) It's a great work
I'm using PHP 7.0.10 (cli) (built: Sep 17 2016 19:11:16) ( NTS )

I'm done for now, i'll test your new version tomorrow in the evening bye

**Comment by JamesTheHacker** [comment] 2016-11-22 22:46
Ok. I should have added the logging by then.

**Comment by randinfo** [comment] 2016-11-23 21:23
Did you added logs ? it's not appeaaring in the added_default_shoutout branch

**Comment by JamesTheHacker** [comment] 2016-11-24 09:10
@randinfo on the case this morning. I had a late night last at work and didn't get time.

**Comment by randinfo** [comment] 2016-11-24 12:06
No problem 👍

**Comment by JamesTheHacker** [comment] 2016-11-27 00:07
Done. Waiting to merge.

**Closed as completed** 2016-11-29 09:13 UTC
